### ISSUE TITLE
Where are your code?

### ISSUE THREAD

**Issue by ghost** [pyqi-Bilibili/trix_os#1]
## Sorry, I haven't see your source code.

**Comment by zxtsd-github** [comment]
### sorry  ，We are building this project

**Comment by ghost** [comment]
You mean there is no project code at present, it's just a project plan.

**Comment by Snickleblor** [comment]
Wo ist der Kode?

**Comment by Snickleblor** [comment]
Give updates atleast, and update the readme to inform us a bit more about the project.

**Comment by ghost** [comment]
OK, I know.
